### PR TITLE
Migration to .NET 6 with tactical rework and NuGet package update (May 2022)

### PR DESCRIPTION
**Pull request by devpro**
* Migrate ASP.NET applications to .NET 6
* Update NuGet pacjages (May 2022)
* Add ASP.NET Razor sample with integration tests
* Fix invalid indentation in Azure pipeline yaml files
* Dump version to 1.5.0

### CODE REVIEW

**Comment by devpro** [comment]
Linked to issue #284 

@paul-hammant: what do you think of this change?

**Comment by paul-hammant** [comment]
Lots changed, incl whitespace, but I went through it. Solid work

**Review by paul-hammant — APPROVED** [review]

**Comment by devpro** [comment]
> Lots changed, incl whitespace, but I went through it. Solid work

The migration to .NET 6 is a major update and I take the opportunity to improve the codebase with tactical rework actions.

**Comment by devpro** [comment]
@paul-hammant I'm still working on Selenium integration with ASP.NET 6 minimal API. The workaround I implemented for .NET Core 3.1 doesn't work but I think it is not needed anymore. I'm working a new sample that will be included in this PR.

Your feedback in the Issue makes a lot of sense and it's a good thing to review what changed in .NET 6.

**Comment by paul-hammant** [comment]
New Selenium tests look good too.

**Comment by devpro** [comment]
> New Selenium tests look good too.

Thank you @paul-hammant. I found a solution for Selenium testing with ASP.NET 6 minimal API thanks to a blog post.

**Comment by devpro** [comment]
Covers also #286

**Comment by paul-hammant** [comment]
Fantastic work

**Pull request merged**
